# doc: https://docs.github.com/en/actions
# custom: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables
# secrets: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-17

# Defaults
  # cluster name: wk-us-prod-eks
  # cluster region: us-east-2
  # kubectl-version
    # "v1.23.6" *
    # "v1.18.5"
    # https://www.gitclear.com/open_repos/kubernetes/kubernetes/releases

name: 'EKS cluster info'
description: 'Providing default + override option to get cluster info'
inputs:
  cluster-name:
    description: "the cluster name"
    required: false
  cluster-region:
    description: "the cluster region"
    required: false
  kubectl-version:
    description: "kubectl version"
    required: false
    
outputs:
  cluster-name:
    description: "the cluster name"
    value: ${{ steps.cluster.outputs.name }}
  cluster-region:
    description: "the cluster region"
    value: ${{ steps.cluster.outputs.region }}
  kubectl-version:
    description: "the kubectl version"
    value: ${{ steps.kubectl.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: cluster
      run: |
        if [[ "${{ inputs.cluster-name }}" == "" ]]; then
            echo "::set-output name=name::wk-us-prod-eks"
        else
            echo "::set-output name=name::${{ inputs.cluster-name }}"
        fi  
        if [[ "${{ inputs.cluster-region }}" == "us-east-2" ]]; then
            echo "::set-output name=region::"
        else
            echo "::set-output name=region::${{ inputs.cluster-region }}"
        fi  
      shell: bash
    - id: kubectl
      run: |
        if [[ "${{ inputs.kubectl-version }}" == "" ]]; then
            echo "::set-output name=version::v1.23.6"
        else
            echo "::set-output name=version::${{ inputs.kubectl-version }}"
        fi  
      shell: bash