name: Increment Version (Directory.Build.props)

# doc:               https://docs.github.com/en/actions
# variables:         https://docs.github.com/en/actions/learn-github-actions/environment-variables
# secrets:           https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-17
# env:               https://docs.github.com/en/actions/learn-github-actions/environment-variables
# reusable workflow: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows

# samples
#   find . -name package.json -o -name lerna.json | grep -v '^./node_modules/' | grep -v '^./.vscode' | grep -v '^./docs' | grep -v '^./nx'
#   find . -regextype posix-extended -iregex '.*(package|lerna)\.json' | grep -v '^./node_modules/' | grep -v '^./.vscode' | grep -v '^./docs' | grep -v '^./nx'

on: 
  workflow_call:
    inputs:
      criteria: 
        type: string
        description: "find criteria"
        required: false
        default: -name package.json -o -name lerna.json
      basePath:  
        type: string
        description: "base path for searching"
        required: false
        default: .
      author-email:  
        type: string
        description: "Email for commit baseline updates"
        required: false
        default: ci@weknow.network
  
jobs:
  version_increment:
    # if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    name: Increment Version
    runs-on: ubuntu-latest    
  
    steps:
      - id: throw-on-failure
        # if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: weknow-network/weknow-throw-on-failure@v13    
  
      - uses: actions/checkout@v3
    
      - name: Increment Version
        run: |
          find ${{ inputs.basePath }} ${{ inputs.criteria}} | xargs perl -pi -e 's/\"version\":\s*\"([0-9]+)\.([0-9]+)\.([0-9]+)(.*)\"/"\"version\": \"$1.$2.${\( $3+1 )}$4\""/eg' 
        shell: bash

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: CI/CD
          commit_user_email: ${{ inputs.author-email }}
          commit_message: "Increment Version"
          commit_options: '--no-verify'
          push_options: '--no-verify'
          # add_options: '-u'
          # skip_dirty_check: true
          # skip_fetch: true  
          # skip_checkout: true
        
      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v7
      #   with:
      #     author_name: CI/CD
      #     author_email: ${{ inputs.author-email }}
      #     message: "Increment Version"
      #     add: .
      #     push: true
    