name: Validate prefix of repo name (enforce convention)

# doc:               https://docs.github.com/en/actions
# variables:         https://docs.github.com/en/actions/learn-github-actions/environment-variables
# secrets:           https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-17
# env:               https://docs.github.com/en/actions/learn-github-actions/environment-variables
# reusable workflow: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows

on: 
  workflow_call:
    inputs:
      organization:
        type: string
        description: "github organization / user of the repo"
        required: true
      repo-prefix:
        type: string
        description: "expected prefix of the repo name"
        required: true


jobs:
  var:
    name: Repo name validation's variables
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion != 'failure' }}

    steps:
      - name: Full prefix
        id: full-prefix
        run: echo ::set-output name=value::$(echo ${{ inputs.organization }}/${{ inputs.repo-prefix }})
  
    outputs:
      full-prefix: ${{ steps.full-prefix.outputs.value }}

  validate-repo-prefix:
    needs: var
    name: Repo name validation
    runs-on: ubuntu-latest    
    
    steps:    
      - id: throw-on-failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: weknow-network/weknow-throw-on-failure@v8       

      - name: Validate repo name
        if: ${{ !startsWith(github.repository, needs.var.outputs.full-prefix ) }}
        uses: actions/github-script@v5
        with:
          script: |
              core.setFailed('Repo name [${{ github.repository }}] must start with [${{ needs.var.outputs.full-prefix }}]: ${{ startsWith(github.repository, needs.var.outputs.full-prefix) }}')
